import { describe, it, expect } from "vitest";
import {
  generateKanbanMarkdown,
  parseKanbanColumns,
  getNextTaskId,
  rebuildKanban,
} from "../src/kanban";
import {
  KANBAN_FRONTMATTER,
  stripLeadingFrontmatter,
  normalizeKanbanBoard,
  hasCanonicalKanbanFrontmatter,
} from "../src/utils";
import { SESSION_KANBAN_TEMPLATE } from "../src/session";
import type { DocflowConfig } from "../src/types";

describe("kanban frontmatter (Obsidian Kanban plugin recognition)", () => {
  it("generateKanbanMarkdown opens with the canonical frontmatter, no blank line", () => {
    const md = generateKanbanMarkdown({ Backlog: [], Doing: [], Blocked: [], Done: [], Archive: [] }, true);
    expect(md.startsWith("---\nkanban-plugin: board\n---\n")).toBe(true);
    expect(md.startsWith(`${KANBAN_FRONTMATTER}\n`)).toBe(true);
    // the specific bug: a blank line between `---` and the key
    expect(md.startsWith("---\n\n")).toBe(false);
  });

  it("SESSION_KANBAN_TEMPLATE opens with the canonical frontmatter", () => {
    expect(SESSION_KANBAN_TEMPLATE.startsWith(`${KANBAN_FRONTMATTER}\n`)).toBe(true);
    expect(hasCanonicalKanbanFrontmatter(SESSION_KANBAN_TEMPLATE)).toBe(true);
  });

  it("repairs the blank-line-after-fence form", () => {
    const broken = "---\n\nkanban-plugin: board\n\n---\n\n# Tasks · frai-rf\n\n## Backlog\n\n- [ ] keep me\n";
    expect(hasCanonicalKanbanFrontmatter(broken)).toBe(false);
    const fixed = normalizeKanbanBoard(broken);
    expect(fixed.startsWith(`${KANBAN_FRONTMATTER}\n\n`)).toBe(true);
    expect(hasCanonicalKanbanFrontmatter(fixed)).toBe(true);
    expect(fixed).toContain("# Tasks · frai-rf");
    expect(fixed).toContain("- [ ] keep me"); // body preserved
    expect(fixed.match(/kanban-plugin: board/g)?.length).toBe(1); // exactly one
  });

  it("collapses a duplicated frontmatter block into one", () => {
    const doubled = `${KANBAN_FRONTMATTER}\n\n---\n\nkanban-plugin: board\n\n---\n\n# Sessions\n\n## Active\n`;
    const fixed = normalizeKanbanBoard(doubled);
    expect(fixed.match(/^---$/gm)?.length).toBe(2); // one opening, one closing
    expect(fixed.match(/kanban-plugin: board/g)?.length).toBe(1);
    expect(fixed).toContain("# Sessions");
  });

  it("handles CRLF frontmatter", () => {
    const crlf = "---\r\n\r\nkanban-plugin: board\r\n\r\n---\r\n\r\n# Tasks\r\n";
    const fixed = normalizeKanbanBoard(crlf);
    expect(fixed.startsWith(`${KANBAN_FRONTMATTER}\n\n`)).toBe(true);
    expect(fixed).toContain("# Tasks");
  });

  it("stripLeadingFrontmatter leaves body without frontmatter untouched", () => {
    const body = "# Tasks\n\n## Backlog\n";
    expect(stripLeadingFrontmatter(body)).toBe(body);
  });

  it("a board with no frontmatter at all gains it", () => {
    const noFm = "# Tasks\n\n## Backlog\n\n- [ ] task\n";
    expect(hasCanonicalKanbanFrontmatter(noFm)).toBe(false);
    expect(hasCanonicalKanbanFrontmatter(normalizeKanbanBoard(noFm))).toBe(true);
  });
});

describe("kanban", () => {
  describe("generateKanbanMarkdown", () => {
    it("generates a valid kanban board with all sections", () => {
      const md = generateKanbanMarkdown(
        {
          Backlog: [],
          Doing: [],
          Blocked: [],
          Done: [],
          Archive: [],
        },
        true
      );
      expect(md).toContain("# Tasks");
      expect(md).toContain("## Backlog");
      expect(md).toContain("## Doing");
      expect(md).toContain("## Blocked");
      expect(md).toContain("## Done");
      expect(md).toContain("## Archive");
      expect(md).toContain("_Auto-generated by docflow_");
    });

    it("excludes Backlog when includeBacklog is false", () => {
      const md = generateKanbanMarkdown(
        {
          Backlog: [],
          Doing: [],
          Blocked: [],
          Done: [],
          Archive: [],
        },
        false
      );
      expect(md).not.toContain("## Backlog");
    });

    it("includes task text for backlog tasks", () => {
      const md = generateKanbanMarkdown(
        {
          Backlog: [
            {
              id: "TODO-001",
              column: "Backlog",
              text: "Implement login",
              sessions: [],
              createdAt: "2025-01-01T00:00:00.000Z",
              updatedAt: "2025-01-01T00:00:00.000Z",
            },
          ],
          Doing: [],
          Blocked: [],
          Done: [],
          Archive: [],
        },
        true
      );
      expect(md).toContain("- [ ] Implement login");
    });

    it("includes task ID and text for done tasks", () => {
      const md = generateKanbanMarkdown(
        {
          Backlog: [],
          Doing: [],
          Blocked: [],
          Done: [
            {
              id: "TODO-001",
              column: "Done",
              text: "Implemented login",
              sessions: ["session-1"],
              createdAt: "2025-01-01T00:00:00.000Z",
              updatedAt: "2025-01-01T01:00:00.000Z",
            },
          ],
          Archive: [],
        },
        true
      );
      expect(md).toContain("- [x] **TODO-001** Implemented login");
    });

    it("shows blocked reason on tasks", () => {
      const md = generateKanbanMarkdown(
        {
          Backlog: [],
          Doing: [
            {
              id: "TODO-002",
              column: "Doing",
              text: "Fix bug",
              sessions: [],
              createdAt: "2025-01-01T00:00:00.000Z",
              updatedAt: "2025-01-01T00:00:00.000Z",
              blockedReason: "Waiting on API key",
            },
          ],
          Blocked: [],
          Done: [],
          Archive: [],
        },
        true
      );
      expect(md).toContain("**BLOCKED**: Waiting on API key");
    });
  });

  describe("parseKanbanColumns", () => {
    it("parses an empty kanban board", () => {
      const md = generateKanbanMarkdown(
        {
          Backlog: [],
          Doing: [],
          Blocked: [],
          Done: [],
          Archive: [],
        },
        true
      );
      const columns = parseKanbanColumns(md);
      expect(Object.keys(columns)).toContain("Backlog");
      expect(Object.keys(columns)).toContain("Doing");
      expect(columns["Backlog"]).toHaveLength(0);
      expect(columns["Doing"]).toHaveLength(0);
    });

    it("parses tasks with text correctly", () => {
      const content = `# Tasks

## Backlog

- [ ] Implement login

## Doing

- [x] **TODO-001** Fix bug

## Done

## Archive
`;
      const columns = parseKanbanColumns(content);
      expect(columns["Backlog"]).toHaveLength(1);
      expect(columns["Backlog"][0].text).toBe("Implement login");
    });

    it("parses tasks with blocked reason", () => {
      // Use em-dash (—) and **BLOCKED** to match the parsing regex
      // This matches what generateKanbanMarkdown outputs
      const content = `# Tasks

## Doing

- [x] **TODO-001** Implement login — **BLOCKED**: Waiting on API key

## Done

## Archive
`;
      const columns = parseKanbanColumns(content);
      expect(columns["Doing"]).toHaveLength(1);
      expect(columns["Doing"][0].blockedReason).toBe("Waiting on API key");
      // Text includes the checkbox prefix from the line - that's expected
      expect(columns["Doing"][0].text).toContain("Implement login");
    });

    it("parses tasks with no optional fields", () => {
      const content = `# Tasks

## Backlog

- [ ] Simple task

## Doing

## Done

## Archive
`;
      const columns = parseKanbanColumns(content);
      expect(columns["Backlog"]).toHaveLength(1);
      expect(columns["Backlog"][0].text).toBe("Simple task");
      expect(columns["Backlog"][0].sessions).toEqual([]);
    });

    it("handles content with no recognized columns", () => {
      const columns = parseKanbanColumns("# No tasks here\n");
      expect(Object.keys(columns)).toHaveLength(5);
      expect(columns["Backlog"]).toEqual([]);
    });

    it("parses multiple tasks in a column", () => {
      const content = `# Tasks

## Backlog

- [ ] Task one
- [ ] Task two

## Doing

## Done

## Archive
`;
      const columns = parseKanbanColumns(content);
      expect(columns["Backlog"]).toHaveLength(2);
      expect(columns["Backlog"][0].text).toBe("Task one");
      expect(columns["Backlog"][1].text).toBe("Task two");
    });
  });

  describe("getNextTaskId", () => {
    it("starts at TODO-001 when no tasks exist", () => {
      expect(getNextTaskId("# Tasks\n")).toBe("TODO-001");
    });

    it("increments from highest existing ID", () => {
      const content = `# Tasks

- [ ] TODO-001: old
- [x] **TODO-003** newer
`;
      expect(getNextTaskId(content)).toBe("TODO-004");
    });

    it("handles non-sequential IDs", () => {
      const content = `# Tasks

- [ ] TODO-010: high
`;
      expect(getNextTaskId(content)).toBe("TODO-011");
    });

    it("handles mixed content", () => {
      const content = `# Tasks

## Backlog

- [ ] TODO-005: backlog task

## Doing

- [x] **TODO-002** doing task

## Done
`;
      expect(getNextTaskId(content)).toBe("TODO-006");
    });
  });

  describe("rebuildKanban", () => {
    it("rebuilds tasks file with new column content", () => {
      const columns: Record<string, any> = {
        Backlog: [
          {
            id: "TODO-001",
            column: "Backlog",
            text: "Test task",
            sessions: [],
            createdAt: "2025-01-01T00:00:00.000Z",
            updatedAt: "2025-01-01T00:00:00.000Z",
          },
        ],
        Doing: [],
        Blocked: [],
        Done: [],
        Archive: [],
      };

      const md = generateKanbanMarkdown(columns, true);
      expect(md).toContain("- [ ] Test task");
      expect(md).toContain("## Backlog");
    });
  });
});
