import { writeFileSync, readdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import type { DocflowConfig } from "./types";
import { generateKanbanMarkdown, parseKanbanColumns, getNextTaskId } from "./kanban";
import { getProjectPath, safeRead, nowISO, ensureDir, readDoc, writeDoc } from "./utils";

// ────────────────────────────────────────────────────────────────────────────
// Briefing & Context
// ────────────────────────────────────────────────────────────────────────────

export function generateBriefing(config: DocflowConfig, slug: string): string {
  const plan = safeRead(getProjectPath(config, slug, "docflow/<slug>/Plan.md"));
  const design = safeRead(getProjectPath(config, slug, "docflow/<slug>/Design.md"));
  const decisions = safeRead(getProjectPath(config, slug, "docflow/<slug>/Decisions.md"));

  let result = "";
  if (plan) {
    const lines = plan.split("\n").slice(-10);
    result += `### Plan (latest)\n${lines.join("\n").slice(0, 500)}\n\n`;
  }
  if (design) {
    const lines = design.split("\n").slice(-10);
    result += `### Design (latest)\n${lines.join("\n").slice(0, 500)}\n\n`;
  }
  if (decisions) {
    const lines = decisions.split("\n").slice(-10);
    result += `### Decisions\n${lines.join("\n").slice(0, 500)}\n\n`;
  }
  return result;
}

export function regenerateContextIndex(config: DocflowConfig, slug: string): void {
  const plan = safeRead(getProjectPath(config, slug, "docflow/<slug>/Plan.md"));
  const design = safeRead(getProjectPath(config, slug, "docflow/<slug>/Design.md"));

  const lines = [
    "# Project Context Index",
    "",
    `_Auto-generated by docflow on ${nowISO()}`,
    "",
    "## Documents",
    "",
    `- [[Plan.md]] ${plan ? "— *Updated*" : "— *Not set*"}`,
    `- [[Design.md]] ${design ? "— *Updated*" : "— *Not set*"}`,
    "- [[Tasks.md]]",
    "- [[Decisions.md]]",
    "",
    "## Instructions",
    "",
    '- Planning decisions → docflow_write (plan, "one paragraph")',
    '- Technical decisions → docflow_write (design, "one paragraph")',
    '- Override AI → docflow_write (decisions, structured entry)',
    '- Claim work → docflow_task (claim, "exact task text")',
    "- Done → docflow_task (done)",
    '- Blocked → docflow_task (block, "reason")',
    "",
  ];

  const path = getProjectPath(config, slug, "docflow/<slug>/_Context.md");
  if (path) writeFileSync(path, lines.join("\n"), "utf-8");
}

export function regenerateMasterIndex(config: DocflowConfig): void {
  const vaultPath = config.vaultPath || resolve(process.env.HOME || ".", "Documents", "vault");
  const indexPath = resolve(vaultPath, "docflow/_Index.md");
  ensureDir(dirname(indexPath));

  let md = "# Projects\n\n";

  for (const [slug, proj] of Object.entries(config.projects)) {
    const tasks = safeRead(getProjectPath(config, slug, "docflow/<slug>/Tasks.md"));
    const sessions = safeRead(getProjectPath(config, slug, "docflow/<slug>/Sessions.md"));

    const hasDoing = tasks?.includes("## Doing") && tasks.split("## Doing")[1]?.includes("- [x]");
    const hasActive = sessions?.includes("## Active");

    if (hasActive) {
      md += `**HOT**: **${proj.name}** ([[${slug}]]/)\n`;
    } else if (hasDoing) {
      md += `**WARM**: **${proj.name}** ([[${slug}]]/)\n`;
    } else {
      md += `**COLD**: **${proj.name}** ([[${slug}]]/)\n`;
    }
  }

  if (md === "# Projects\n\n") md += "_No projects yet._\n";

  writeFileSync(indexPath, md, "utf-8");
}

export function ensureProjectDocs(config: DocflowConfig, slug: string): void {
  const base = getProjectPath(config, slug, "docflow/<slug>/");
  if (!base) return;
  ensureDir(base);

  const files = readdirSync(base);
  if (!files.includes("Tasks.md")) {
    writeDoc(
      config,
      slug,
      "Tasks.md",
      generateKanbanMarkdown({ Backlog: [], Doing: [], Blocked: [], Done: [], Archive: [] }, true)
    );
  }
  if (!files.includes("Sessions.md")) {
    writeDoc(config, slug, "Sessions.md", "# Sessions\n\n## Active\n\n## Idle\n\n## Stale\n\n## Ended\n\n");
  }
  if (!files.includes("_Context.md")) {
    regenerateContextIndex(config, slug);
  }
  if (!files.includes("Decisions.md")) {
    writeDoc(config, slug, "Decisions.md", "# Decision Log\n\n_No decisions yet._\n");
  }
}
