import type { DocflowConfig } from "./types";
import { writeDoc } from "./utils";
import type { TaskRecord } from "./types";

// ────────────────────────────────────────────────────────────────────────────
// Kanban Markdown Generation
// ────────────────────────────────────────────────────────────────────────────

const ALL_COLUMNS = ["Backlog", "Doing", "Blocked", "Done", "Archive"] as const;

export function generateKanbanMarkdown(columns: Record<string, TaskRecord[]>, includeBacklog: boolean = true): string {
  let md = "---\nkanban-plugin: board\n---\n\n# Tasks\n\n_Auto-generated by docflow_\n\n";

  for (const col of ALL_COLUMNS) {
    if (!includeBacklog && col === "Backlog") continue;
    const tasks = columns[col] || [];
    md += `## ${col}\n\n`;
    if (tasks.length === 0) {
      md += "_Empty_\n\n";
    } else {
      for (const task of tasks) {
        if (col === "Backlog") {
          md += `- [ ] ${task.text}\n`;
          if (task.why) md += `  - Why: ${task.why}\n`;
          if (task.implementation_hints) md += `  - Hints: ${task.implementation_hints}\n`;
        } else {
          md += `- [x] **${task.id}** ${task.text}`;
          if (task.sessions.length > 0) md += ` (@${shortenId(task.sessions[0], 4)})`;
          if (task.blockedReason) md += ` — **BLOCKED**: ${task.blockedReason}`;
          md += "\n";
        }
      }
      md += "\n";
    }
  }

  return md;
}

function shortenId(id: string, length = 5): string {
  return id.replace(/[^a-zA-Z0-9]/g, "").slice(0, length);
}

export function parseKanbanColumns(content: string): Record<string, TaskRecord[]> {
  const columns: Record<string, TaskRecord[]> = {
    Backlog: [],
    Doing: [],
    Blocked: [],
    Done: [],
    Archive: [],
  };

  if (!content) return columns;

  const lines = content.split("\n");
  let currentColumn: string | null = null;

  for (const line of lines) {
    // Match column headers: ## Backlog, ## Doing, etc.
    // Also match partial headers like "## Doing\n## Blocked" (greedy match)
    const headerMatch = line.match(/^##\s+(Backlog|Doing|Blocked|Done|Archive)\b/);
    if (headerMatch) {
      currentColumn = headerMatch[1];
      continue;
    }

    // Task in reconciler-owned columns (Done, Archive, etc.)
    if (line.match(/^-\s*\[x\]\s*\*\*/)) {
      if (!currentColumn) continue;
      // Parse: - [x] **TODO-001** Implement login (@sess) — BLOCKED: reason
      const idMatch = line.match(/\*\*(TODO-\d+)\*\*/);
      const id = idMatch?.[1] || `TODO-${Date.now()}`;
      const afterId = line.replace(/\*\*TODO-\d+\*\*/, "").trim();
      // Remove session refs: (@sess)
      let text = afterId.replace(/\s*\(@\w+\)/g, "").trim();
      // Remove blocked reason from text
      let blockedReason: string | undefined;
      const blockMatch = text.match(/\s*—\s*\*\*BLOCKED\*\*:\s*(.+)$/);
      if (blockMatch) {
        blockedReason = blockMatch[1];
        text = text.replace(/\s*—\s*\*\*BLOCKED\*\*:\s*.+$/, "").trim();
      }

      columns[currentColumn].push({
        id,
        column: currentColumn as TaskRecord["column"],
        text,
        sessions: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        blockedReason,
      });
    } else if (line.match(/^-\s*\[ \]\s*/)) {
      // Backlog task (user-owned)
      if (!currentColumn) continue;
      const text = line.replace(/^- \[ \]\s*/, "").trim();
      columns["Backlog"].push({
        id: `TODO-${Date.now()}`,
        column: "Backlog",
        text,
        sessions: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
    }
  }

  return columns;
}

export function getNextTaskId(content: string): string {
  const matches = content.match(/(TODO|TASK)-(\d+)/g);
  if (!matches || matches.length === 0) return "TODO-001";
  const max = Math.max(
    ...matches.map((m) => {
      const parts = m.split("-");
      return parseInt(parts[1]);
    })
  );
  return `TODO-${String(max + 1).padStart(3, "0")}`;
}

export function rebuildKanban(config: DocflowConfig, slug: string, columns: Record<string, TaskRecord[]>): void {
  const md = generateKanbanMarkdown(columns, true);
  writeDoc(config, slug, "Tasks.md", md);
}
